apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  # lables of deployment resource
  labels:
    app: backend
    tier: backend
    purpose: expense
    version:  blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      purpose: expense
      version:  blue
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        purpose: expense
        version:  blue
    spec:
      containers:
      - name: nginx
        image: balaguru20/backend:1.0.0
        envFrom:
        - configMapRef:
          name: backend