kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector: # labels are used as selectors
    app: backend
    tier: backend
    purpose: expense
    version: blue
  ports:
  - protocol: TCP
    port: 8080 # service port, we give whatever port we want
    targetPort: 8080 # It is mondatory 